/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  const CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String _kFontPkg = null;

  static const IconData chicken_leg =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife_fork =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill =
      IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_paypal =
      IconData(0xf1f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_stripe =
      IconData(0xf1f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish =
      IconData(0xf578, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_cheers =
      IconData(0xf79f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
