/// Flutter icons Food
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Food
///      fonts:
///       - asset: fonts/Food.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FoodIcons {
  const FoodIcons._();

  static const _kFontFam = 'FoodIcons';
  static const String _kFontPkg = null;

  static const IconData food =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken_leg =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife_fork =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat =
      IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish =
      IconData(0xf578, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pastafarianism =
      IconData(0xf67b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carrot =
      IconData(0xf787, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_cheers =
      IconData(0xf79f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pepper_hot =
      IconData(0xf816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
